run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters: [revive]
      text: "package-comments"
    - linters: [revive]
      text: "exported:"
    - linters: [staticcheck]
      text: "SA1019"
    - linters: [revive]
      text: "unused-parameter"
