run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
