version: '3.3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/budget-bot
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/budget-bot
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    environment:
      - APP_ENV=dev
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db
      - SYMFONY_DEPRECATIONS_HELPER=disabled=1
    restart: unless-stopped

  composer:
    image: composer:latest
    volumes:
      - .:/var/www/budget-bot
    working_dir: /var/www/budget-bot
    command: composer install --ignore-platform-reqs --no-scripts 