// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: budget/v1/fx.proto

package budgetv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a single FX rate quote (from → to) as of specific date/time
type FxRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromCurrencyCode string                 `protobuf:"bytes,1,opt,name=from_currency_code,json=fromCurrencyCode,proto3" json:"from_currency_code,omitempty"` // e.g. "USD"
	ToCurrencyCode   string                 `protobuf:"bytes,2,opt,name=to_currency_code,json=toCurrencyCode,proto3" json:"to_currency_code,omitempty"`       // e.g. "RUB"
	RateDecimal      string                 `protobuf:"bytes,3,opt,name=rate_decimal,json=rateDecimal,proto3" json:"rate_decimal,omitempty"`                  // e.g. "92.3456"
	AsOf             *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	Provider         string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"` // e.g. "ecb", "cbr", "manual"
}

func (x *FxRate) Reset() {
	*x = FxRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_budget_v1_fx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FxRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FxRate) ProtoMessage() {}

func (x *FxRate) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1_fx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FxRate.ProtoReflect.Descriptor instead.
func (*FxRate) Descriptor() ([]byte, []int) {
	return file_budget_v1_fx_proto_rawDescGZIP(), []int{0}
}

func (x *FxRate) GetFromCurrencyCode() string {
	if x != nil {
		return x.FromCurrencyCode
	}
	return ""
}

func (x *FxRate) GetToCurrencyCode() string {
	if x != nil {
		return x.ToCurrencyCode
	}
	return ""
}

func (x *FxRate) GetRateDecimal() string {
	if x != nil {
		return x.RateDecimal
	}
	return ""
}

func (x *FxRate) GetAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOf
	}
	return nil
}

func (x *FxRate) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type GetRateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromCurrencyCode string                 `protobuf:"bytes,1,opt,name=from_currency_code,json=fromCurrencyCode,proto3" json:"from_currency_code,omitempty"`
	ToCurrencyCode   string                 `protobuf:"bytes,2,opt,name=to_currency_code,json=toCurrencyCode,proto3" json:"to_currency_code,omitempty"`
	AsOf             *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"` // date at which to get the rate (truncate to day server-side if needed)
}

func (x *GetRateRequest) Reset() {
	*x = GetRateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_budget_v1_fx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateRequest) ProtoMessage() {}

func (x *GetRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1_fx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateRequest.ProtoReflect.Descriptor instead.
func (*GetRateRequest) Descriptor() ([]byte, []int) {
	return file_budget_v1_fx_proto_rawDescGZIP(), []int{1}
}

func (x *GetRateRequest) GetFromCurrencyCode() string {
	if x != nil {
		return x.FromCurrencyCode
	}
	return ""
}

func (x *GetRateRequest) GetToCurrencyCode() string {
	if x != nil {
		return x.ToCurrencyCode
	}
	return ""
}

func (x *GetRateRequest) GetAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOf
	}
	return nil
}

type GetRateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rate *FxRate `protobuf:"bytes,1,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *GetRateResponse) Reset() {
	*x = GetRateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_budget_v1_fx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateResponse) ProtoMessage() {}

func (x *GetRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1_fx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateResponse.ProtoReflect.Descriptor instead.
func (*GetRateResponse) Descriptor() ([]byte, []int) {
	return file_budget_v1_fx_proto_rawDescGZIP(), []int{2}
}

func (x *GetRateResponse) GetRate() *FxRate {
	if x != nil {
		return x.Rate
	}
	return nil
}

type UpsertRateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rate *FxRate `protobuf:"bytes,1,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *UpsertRateRequest) Reset() {
	*x = UpsertRateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_budget_v1_fx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRateRequest) ProtoMessage() {}

func (x *UpsertRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1_fx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRateRequest.ProtoReflect.Descriptor instead.
func (*UpsertRateRequest) Descriptor() ([]byte, []int) {
	return file_budget_v1_fx_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertRateRequest) GetRate() *FxRate {
	if x != nil {
		return x.Rate
	}
	return nil
}

type UpsertRateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rate *FxRate `protobuf:"bytes,1,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *UpsertRateResponse) Reset() {
	*x = UpsertRateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_budget_v1_fx_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRateResponse) ProtoMessage() {}

func (x *UpsertRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1_fx_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRateResponse.ProtoReflect.Descriptor instead.
func (*UpsertRateResponse) Descriptor() ([]byte, []int) {
	return file_budget_v1_fx_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertRateResponse) GetRate() *FxRate {
	if x != nil {
		return x.Rate
	}
	return nil
}

type BatchGetRatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromCurrencyCodes []string               `protobuf:"bytes,1,rep,name=from_currency_codes,json=fromCurrencyCodes,proto3" json:"from_currency_codes,omitempty"`
	ToCurrencyCode    string                 `protobuf:"bytes,2,opt,name=to_currency_code,json=toCurrencyCode,proto3" json:"to_currency_code,omitempty"`
	AsOf              *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
}

func (x *BatchGetRatesRequest) Reset() {
	*x = BatchGetRatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_budget_v1_fx_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGetRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRatesRequest) ProtoMessage() {}

func (x *BatchGetRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1_fx_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRatesRequest.ProtoReflect.Descriptor instead.
func (*BatchGetRatesRequest) Descriptor() ([]byte, []int) {
	return file_budget_v1_fx_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetRatesRequest) GetFromCurrencyCodes() []string {
	if x != nil {
		return x.FromCurrencyCodes
	}
	return nil
}

func (x *BatchGetRatesRequest) GetToCurrencyCode() string {
	if x != nil {
		return x.ToCurrencyCode
	}
	return ""
}

func (x *BatchGetRatesRequest) GetAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOf
	}
	return nil
}

type BatchGetRatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rates []*FxRate `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
}

func (x *BatchGetRatesResponse) Reset() {
	*x = BatchGetRatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_budget_v1_fx_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGetRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRatesResponse) ProtoMessage() {}

func (x *BatchGetRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1_fx_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRatesResponse.ProtoReflect.Descriptor instead.
func (*BatchGetRatesResponse) Descriptor() ([]byte, []int) {
	return file_budget_v1_fx_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetRatesResponse) GetRates() []*FxRate {
	if x != nil {
		return x.Rates
	}
	return nil
}

var File_budget_v1_fx_proto protoreflect.FileDescriptor

var file_budget_v1_fx_proto_rawDesc = []byte{
	0x0a, 0x12, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x78, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xd0, 0x01, 0x0a, 0x06, 0x46, 0x78, 0x52, 0x61, 0x74, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x66,
	0x72, 0x6f, 0x6d, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x66, 0x72, 0x6f, 0x6d, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x6f, 0x5f,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x6f, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x65, 0x63, 0x69,
	0x6d, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x61, 0x74, 0x65, 0x44,
	0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x2f, 0x0a, 0x05, 0x61, 0x73, 0x5f, 0x6f, 0x66, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x04, 0x61, 0x73, 0x4f, 0x66, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x22, 0x99, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x66, 0x72, 0x6f, 0x6d, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x6f, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x74, 0x6f, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2f,
	0x0a, 0x05, 0x61, 0x73, 0x5f, 0x6f, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x61, 0x73, 0x4f, 0x66, 0x22,
	0x38, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x78, 0x52,
	0x61, 0x74, 0x65, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x22, 0x3a, 0x0a, 0x11, 0x55, 0x70, 0x73,
	0x65, 0x72, 0x74, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25,
	0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62,
	0x75, 0x64, 0x67, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x78, 0x52, 0x61, 0x74, 0x65, 0x52,
	0x04, 0x72, 0x61, 0x74, 0x65, 0x22, 0x3b, 0x0a, 0x12, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x72,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x75, 0x64, 0x67,
	0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x78, 0x52, 0x61, 0x74, 0x65, 0x52, 0x04, 0x72, 0x61,
	0x74, 0x65, 0x22, 0xa1, 0x01, 0x0a, 0x14, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x52,
	0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x66,
	0x72, 0x6f, 0x6d, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x66, 0x72, 0x6f, 0x6d, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x74,
	0x6f, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x6f, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x61, 0x73, 0x5f, 0x6f, 0x66, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x04, 0x61, 0x73, 0x4f, 0x66, 0x22, 0x40, 0x0a, 0x15, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47,
	0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x27, 0x0a, 0x05, 0x72, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x78, 0x52, 0x61, 0x74,
	0x65, 0x52, 0x05, 0x72, 0x61, 0x74, 0x65, 0x73, 0x32, 0xec, 0x01, 0x0a, 0x09, 0x46, 0x78, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74,
	0x65, 0x12, 0x19, 0x2e, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x62,
	0x75, 0x64, 0x67, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x55, 0x70, 0x73, 0x65,
	0x72, 0x74, 0x52, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x52,
	0x61, 0x74, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x72, 0x6f, 0x6e, 0x34, 0x38,
	0x2f, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x2f, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x62,
	0x75, 0x64, 0x67, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_budget_v1_fx_proto_rawDescOnce sync.Once
	file_budget_v1_fx_proto_rawDescData = file_budget_v1_fx_proto_rawDesc
)

func file_budget_v1_fx_proto_rawDescGZIP() []byte {
	file_budget_v1_fx_proto_rawDescOnce.Do(func() {
		file_budget_v1_fx_proto_rawDescData = protoimpl.X.CompressGZIP(file_budget_v1_fx_proto_rawDescData)
	})
	return file_budget_v1_fx_proto_rawDescData
}

var file_budget_v1_fx_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_budget_v1_fx_proto_goTypes = []interface{}{
	(*FxRate)(nil),                // 0: budget.v1.FxRate
	(*GetRateRequest)(nil),        // 1: budget.v1.GetRateRequest
	(*GetRateResponse)(nil),       // 2: budget.v1.GetRateResponse
	(*UpsertRateRequest)(nil),     // 3: budget.v1.UpsertRateRequest
	(*UpsertRateResponse)(nil),    // 4: budget.v1.UpsertRateResponse
	(*BatchGetRatesRequest)(nil),  // 5: budget.v1.BatchGetRatesRequest
	(*BatchGetRatesResponse)(nil), // 6: budget.v1.BatchGetRatesResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_budget_v1_fx_proto_depIdxs = []int32{
	7,  // 0: budget.v1.FxRate.as_of:type_name -> google.protobuf.Timestamp
	7,  // 1: budget.v1.GetRateRequest.as_of:type_name -> google.protobuf.Timestamp
	0,  // 2: budget.v1.GetRateResponse.rate:type_name -> budget.v1.FxRate
	0,  // 3: budget.v1.UpsertRateRequest.rate:type_name -> budget.v1.FxRate
	0,  // 4: budget.v1.UpsertRateResponse.rate:type_name -> budget.v1.FxRate
	7,  // 5: budget.v1.BatchGetRatesRequest.as_of:type_name -> google.protobuf.Timestamp
	0,  // 6: budget.v1.BatchGetRatesResponse.rates:type_name -> budget.v1.FxRate
	1,  // 7: budget.v1.FxService.GetRate:input_type -> budget.v1.GetRateRequest
	3,  // 8: budget.v1.FxService.UpsertRate:input_type -> budget.v1.UpsertRateRequest
	5,  // 9: budget.v1.FxService.BatchGetRates:input_type -> budget.v1.BatchGetRatesRequest
	2,  // 10: budget.v1.FxService.GetRate:output_type -> budget.v1.GetRateResponse
	4,  // 11: budget.v1.FxService.UpsertRate:output_type -> budget.v1.UpsertRateResponse
	6,  // 12: budget.v1.FxService.BatchGetRates:output_type -> budget.v1.BatchGetRatesResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_budget_v1_fx_proto_init() }
func file_budget_v1_fx_proto_init() {
	if File_budget_v1_fx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_budget_v1_fx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FxRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_budget_v1_fx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_budget_v1_fx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_budget_v1_fx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertRateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_budget_v1_fx_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertRateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_budget_v1_fx_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchGetRatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_budget_v1_fx_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchGetRatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_budget_v1_fx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_budget_v1_fx_proto_goTypes,
		DependencyIndexes: file_budget_v1_fx_proto_depIdxs,
		MessageInfos:      file_budget_v1_fx_proto_msgTypes,
	}.Build()
	File_budget_v1_fx_proto = out.File
	file_budget_v1_fx_proto_rawDesc = nil
	file_budget_v1_fx_proto_goTypes = nil
	file_budget_v1_fx_proto_depIdxs = nil
}
