categories:
    expenses:
        food:
            - еда
            - продукты
            - готовая еда
            - ресторан
            - кафе
            - фастфуд
        transport:
            - такси
            - метро
            - автобус
            - транспорт
        entertainment:
            - кино
            - театр
            - развлечения
        household:
            - хозтовары
            - бытовые
            - дом
        health:
            - аптека
            - врач
            - медицина
        clothes:
            - одежда
            - обувь
            - аксессуары
    income:
        salary:
            - зарплата
            - аванс
            - премия
        freelance:
            - фриланс
            - подработка
        investment:
            - инвестиции
            - дивиденды
            - проценты
        other:
            - прочее
            - разное
            - другое 