parameters:
    telegram_bot_token: '%env(TELEGRAM_BOT_TOKEN)%'
    telegram_bot_username: '%env(TELEGRAM_BOT_USERNAME)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\TelegramBotService:
        arguments:
            $botToken: '%telegram_bot_token%'
            $botUsername: '%telegram_bot_username%'

    App\Service\Command\:
        resource: '../src/Service/Command'
        exclude:
            - '../src/Service/Command/AbstractCommand.php'
            - '../src/Service/Command/CommandInterface.php'
        tags: ['app.command']

    App\Service\StateHandler\:
        resource: '../src/Service/StateHandler'
        exclude:
            - '../src/Service/StateHandler/StateHandlerInterface.php'
        tags: ['app.state_handler']

    App\Service\CommandRegistry:
        arguments:
            $commands: !tagged_iterator app.command

    App\Service\StateHandler\StateHandlerRegistry:
        arguments:
            $handlers: !tagged_iterator app.state_handler 