parameters:
    telegram_bot_token: 'test_token'
    telegram_bot_username: 'test_bot'
    google_credentials_path: 'test_credentials.json'
    google_service_account_email: 'test@example.com'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Service\TelegramApiServiceInterface:
        class: App\Tests\Mock\TelegramApiMock

    App\Service\Google\GoogleApiClientInterface:
        class: App\Tests\Mock\TestGoogleApiClient

    App\Service\Chat\ChatInterface:
        class: App\Tests\Mock\ChatMock

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Service/TelegramApiService.php'
            - '../src/Service/Google/GoogleApiClient.php' 