imports:
    - { resource: services.yaml }

parameters:
    telegram_bot_token: 'test_token'
    telegram_bot_username: 'test_bot'
    google_credentials_path: 'test_credentials.json'
    google_service_account_email: 'test@example.com'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # Test mocks
    App\Tests\Mock\TelegramApiMock:
        public: true

    App\Tests\Mock\TestGoogleApiClient:
        public: true

    # Override API services with mocks
    App\Service\TelegramApiServiceInterface:
        alias: App\Tests\Mock\TelegramApiMock

    App\Service\Google\GoogleApiClientInterface:
        alias: App\Tests\Mock\TestGoogleApiClient 