parameters:
    telegram.bot_token: '%env(TELEGRAM_BOT_TOKEN)%'
    telegram.bot_username: '%env(TELEGRAM_BOT_USERNAME)%'
    google.credentials_path: '%env(GOOGLE_SHEETS_CREDENTIALS_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php' 