parameters:
    telegram.bot_token: '%env(TELEGRAM_BOT_TOKEN)%'
    telegram.bot_username: '%env(TELEGRAM_BOT_USERNAME)%'
    google.credentials_path: '%env(GOOGLE_SHEETS_CREDENTIALS_PATH)%'
    google.service_account_email: '%env(GOOGLE_SERVICE_ACCOUNT_EMAIL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Command\SetWebhookCommand:
        arguments:
            $botToken: '%telegram.bot_token%'
            $botUsername: '%telegram.bot_username%'

    App\Service\TelegramBotService:
        arguments:
            $botToken: '%telegram.bot_token%'
            $botUsername: '%telegram.bot_username%'

    App\Service\GoogleSheetsService:
        arguments:
            $credentialsPath: '%google.credentials_path%'
            $serviceAccountEmail: '%google.service_account_email%' 