services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Tests\:
        resource: '../tests/*'
        exclude:
            - '../tests/bootstrap.php'
            - '../tests/*/DataFixtures/'
        autowire: false
        autoconfigure: false

    App\Service\TransactionHandler:
        class: App\Tests\Mock\TestTransactionHandler
        public: true

    App\Service\Google\GoogleSheetsClient:
        arguments:
            $credentialsPath: '%env(resolve:GOOGLE_CREDENTIALS_PATH)%'
            $serviceAccountEmail: '%env(GOOGLE_SERVICE_ACCOUNT_EMAIL)%'

    App\Tests\Mock\:
        resource: '../tests/Mock/'

    App\Service\TelegramApiServiceInterface:
        class: App\Tests\Mock\TelegramApiMock

    App\Service\TelegramBotService:
        arguments:
            $token: 'test_token'
            $username: 'test_username' 