name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Tidy
        run: go mod tidy
      - name: Build (default)
        run: go build ./cmd/bot
      - name: Build (withgrpc)
        run: go build -tags withgrpc ./cmd/bot
      - name: Test
        run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.54.2
          args: --timeout=3m